Resit Project/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Resit_Project.Models
{
    public class Staff
    {
        [Key]
        public int StaffId { get; set; }
        [Required]
        [StringLength(50,MinimumLength = 10)]
        public string FullName { get; set; }
        public Gender Gender { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Birthday { get; set; }
        [Required]
        public string Address { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        public int TotalPrice { get; set; }
        public int Phone { get; set; }
        public int PositionId { get; set; }
        public byte[] Image { get; set; }
        public virtual Position Positions { get; set; }
    }

    public enum Gender
    {
        Male,
        Female
    }
}

Resit Project/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using Resit_Project.Models;

namespace Resit_Project.Controllers
{
    public class StaffsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Staffs
        public ActionResult Index()
        {
            var staffs = db.Staffs.ToList();
            return View(staffs);
        }


        public ActionResult Details(int? id, string name, int? month, int? year)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }

            return View(staff);
        }

        private bool IsDuplicateStaff(Staff staff)
        {
            return db.Staffs.Any(s => s.StaffId != staff.StaffId && s.FullName == staff.FullName && s.Birthday == staff.Birthday);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StaffId,FullName,Gender,Birthday,Address,StartDate,Phone,PositionId")] Staff staff, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                staff.Image = new byte[image.ContentLength];
                image.InputStream.Read(staff.Image, 0, image.ContentLength);
            }

            if (ModelState.IsValid)
            {
                if (staff.Image == null)
                {
                    ModelState.AddModelError("", "Please upload an image");
                    return View(staff);
                }
                if (IsDuplicateStaff(staff))
                {
                    ModelState.AddModelError("", "A staff with the same name and birthday already exists!");
                    return View(staff);
                }

                db.Staffs.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Name");
            return View(staff);
        }
        // GET: Staffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Name");
            return View(staff);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind(Include = "StaffId,FullName,Gender,Birthday,Address,StartDate,Phone,PositionId")] Staff staff, HttpPostedFileBase image)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Staff staffToUpdate = db.Staffs.Find(id);
            if (staffToUpdate == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                if (IsDuplicateStaff(staff))
                {
                    ModelState.AddModelError("", "A staff with the same name and birthday already exists!");
                    return View(staff);
                }
                staffToUpdate.FullName = staff.FullName;
                staffToUpdate.Gender = staff.Gender;
                staffToUpdate.Birthday = staff.Birthday;
                staffToUpdate.Address = staff.Address;
                staffToUpdate.StartDate = staff.StartDate;
                staffToUpdate.Phone = staff.Phone;
                staffToUpdate.PositionId = staff.PositionId;


                if (image != null && image.ContentLength > 0)
                {
                    staffToUpdate.Image = new byte[image.ContentLength];
                    image.InputStream.Read(staffToUpdate.Image, 0, image.ContentLength);
                }

                db.Entry(staffToUpdate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Name");
            return View(staffToUpdate);
        }


        // GET: Staffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Staff staff = db.Staffs.Find(id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Resit Project/Views/Staffs/Create.cshtml
@model Resit_Project.Models.Staff

@{
    ViewBag.Title = "Create";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "breadcrumb-item" })
            @Html.ActionLink("Staff List", "Index", "Staffs", new { area = "" }, new { @class = "breadcrumb-item" })
            <span class="breadcrumb-item active">Create</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h3 class="text-center">Create</h3>
    </div>
    <div class="card-body">
        <div class="col-md-4">
            @using (Html.BeginForm("Create", "Staffs", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Staff</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                            @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PositionId, "Position", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("PositionId", (IEnumerable<SelectListItem>)(ViewBag.Position),
                           new { @class = "w-50" })
                            @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="Image" id="Image" accept=".png,.jpeg,.jpg,.gif,.svg" style="width:100%" />
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-info" />
                            @Html.ActionLink("Back to List", "Index", new { area = "" }, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Resit Project/Views/Staffs/Delete.cshtml
@model Resit_Project.Models.Staff

@{
    ViewBag.Title = "Delete";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "breadcrumb-item" })
            @Html.ActionLink("Staff Lists", "Index", "Staffs", new { area = "" }, new { @class = "breadcrumb-item" })
            <span class="breadcrumb-item active">Delete</span>
        </nav>
    </div>
</div>

<div class="alert alert-danger">
    <h3>Do you wanna delete this?</h3>
</div>

<div class="card">
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FullName)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FullName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Gender)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Birthday)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Birthday)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Phone)
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Positions.Name)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Positions.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-10">
                <img style="width:100px; height:100px;" class="img-responsive full-width" src="data:image/jpg;base64,@Convert.ToBase64String(Model.Image)" />
            </dd>
        </dl>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" />
                @Html.ActionLink("Back", "Index", new { area = "" }, new { @class = "btn btn-primary" })
            </div>
        }
    </div>
</div>

Resit Project/Views/Staffs/Details.cshtml
@model Resit_Project.Models.Staff

@{
    ViewBag.Title = "Details";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "breadcrumb-item" })
            @Html.ActionLink("Staff Lists", "Index", "Staffs", new { area = "" }, new { @class = "breadcrumb-item" })
            <span class="breadcrumb-item active">Details</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h3 class="text-center">Details</h3>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FullName)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.FullName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Gender)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Birthday)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.Birthday)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.Address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Phone)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.Phone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Positions.Name)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.Positions.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Positions.Salary)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.Positions.Salary)
            </dd>

            <dd class="col-sm-10">
                <img style="width:120px; height:100px;" class="img-responsive full-width" src="data:image/jpg;base64,@Convert.ToBase64String(Model.Image)" />
            </dd>
        </dl>
    </div>
</div>
<br />

@using (Html.BeginForm("Details", "Staffs", FormMethod.Get))
{
    <div class="form-group">
        <label for="month">Month:</label>
        <input type="text" class="form-control-sm" name="month" id="month" placeholder="Month"/>

        <label for="year">Year:</label>
        <input type="text" class="form-control-sm" name="year" id="year" placeholder="Year"/>

        <label for="name">Search:</label>
        <input type="text" class="form-control-sm" name="name" id="name" placeholder="Code"/>

        <button type="submit" class="btn btn-primary">Filter</button>
    </div>
    <div class="form-group">

    </div>
    <div class="form-group">

    </div>

}

<h3 class="text-sm-end">Salary: @Html.DisplayFor(model => model.TotalPrice)</h3>

<div>
    <table class="table table-bordered">
        <thead class="table-secondary">
            <tr>
                <th>Code</th>
                <th>Stage</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Date Completed</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var work in ViewBag.Works)
            {
                <tr>
                    <td>@work.Category.Name</td>
                    <td>@work.PriceListName</td>
                    <td>@work.Quantity</td>
                    <td>@work.Price</td>
                    <td>@work.DateCompleted.ToShortDateString()</td>
                    <td>@work.Phone</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Resit Project/Views/Staffs/Edit.cshtml
@model Resit_Project.Models.Staff

@{
    ViewBag.Title = "Edit";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "breadcrumb-item" })
            @Html.ActionLink("Staff List", "Index", "Staffs", new { area = "" }, new { @class = "breadcrumb-item" })
            <span class="breadcrumb-item active">Edit</span>
        </nav>
    </div>
</div>


<div class="card">
    <div class="card-header">
        <h3 class="text-center">Edit</h3>
    </div>

    <div class="card-body">
        <div class="col-md-4">
            @using (Html.BeginForm("Edit", "Staffs", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Staff</h4>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.StaffId)

                <div class="form-group">
                    @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PositionId, "Position", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("PositionId", (IEnumerable<SelectListItem>)(ViewBag.Position),
                       new { @class = "w-50" })
                        @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="Image" id="Image" accept=".png,.jpeg,.jpg,.gif,.svg" style="width:100%" />
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-info" />
                        @Html.ActionLink("Back", "Index", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

Resit Project/Views/Staffs/Index.cshtml
@model IEnumerable<Resit_Project.Models.Staff>

@{
    ViewBag.Title = "Index";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "breadcrumb-item" })
            <span class="breadcrumb-item active">Staff List</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h3 class="text-center">Staff List</h3>
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        @*<select class="custom-select" id="txtposition" name="txtposition" style="min-width: 200px;" asp-items="ViewBag.Combine">
                                 <option selected>CombineStage Name</option>
                            </select>*@
                    </div>
                </div>
            </div>
            <div class="col-lg-6 text-right">
                @Html.ActionLink("Create New", "Create", "Staffs", new { area = "" }, new { @class = "btn btn-primary" })
            </div>
        </div>
        <br />
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead class="table-secondary">
                    <tr>
                        <th>Id</th>
                        <th>FullName</th>
                        <th>Gender</th>
                        <th>StartDate</th>
                        <th>Phone</th>
                        <th>Position</th>
                        <th>Salary</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.StaffId</td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <img style="max-width: 70px" class="img-fluid rounded" src="data:image/jpg;base64,@Convert.ToBase64String(item.Image)" />
                                        <h6 class="m-b-0 m-l-10 p-2">@item.FullName</h6>
                                    </div>
                                </td>
                                <td>
                                    @item.Gender
                                </td>
                                <td>@item.StartDate.ToShortDateString()</td>
                                <td>@item.Phone</td>
                                <td>@item.Positions.Name</td>
                                <td>@item.Positions.Salary</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.StaffId }, new { @class = "btn btn-sm btn-success rounded-0" })
                                    @Html.ActionLink("Details", "Details", new { id = item.StaffId }, new { @class = "btn btn-sm btn-info rounded-0" })
                                    @Html.ActionLink("Delete", "Delete", new { id = item.StaffId }, new { @class = "btn btn-sm btn-danger rounded-0" })
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            @*<div aria-label="Page navigation example">
                    <ul class="pagination">
                        <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="CombineStage" asp-action="Index" />
                    </ul>
                </div>*@
        </div>
    </div>
</div>